# Generated by Django 5.2.3 on 2025-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250627_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]

