# Generated by Django 5.2.3 on 2025-06-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]

